name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     #bring sourcecode to current working direction
      - uses: actions/setup-node@v1   #setup node
        with:
          node-version: 16
      - run: npm ci                   #eg: npm install
      # - run: npm run test
      - run: npm run build
