name: Firebase Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2     #bring sourcecode to current working direction
        - uses: actions/setup-node@v1   #setup node
          with:
            node-version: 16
        - run: npm ci                   #eg: npm install
        - run: npm run build
        - uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
